# -*- coding: utf-8 -*-
"""python-basics-assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Y2xsucfS-R6NJtIKifsZ4Y1wPmVbg17
"""

#Task1
name = "kamal kalyan ambavaram"
age = 19
height = 5.11
is_student = True
print(name, age, height,is_student)


#Task2
print(f"Name:{name} | Age:{age} | Height:{height} | Is_student:{is_student}")

#task3
age = 19
days = 365
months = 12
print("age in months :",age*months)
print("age in days :",age*365)
print("when age is divided by 7 :" ,age % 7)
print("age raised to power of 2 :",age**2)